/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSomRouteImport } from './routes/_authenticated/som'
import { Route as AuthenticatedMusicosRouteImport } from './routes/_authenticated/musicos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicTimeRouteImport } from './routes/api/public/time'
import { Route as AuthenticatedAdminSongsIdRouteImport } from './routes/_authenticated/admin.songs.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSomRoute = AuthenticatedSomRouteImport.update({
  id: '/som',
  path: '/som',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicosRoute = AuthenticatedMusicosRouteImport.update({
  id: '/musicos',
  path: '/musicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTimeRoute = ApiPublicTimeRouteImport.update({
  id: '/api/public/time',
  path: '/api/public/time',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSongsIdRoute =
  AuthenticatedAdminSongsIdRouteImport.update({
    id: '/admin/songs/$id',
    path: '/admin/songs/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/musicos': typeof AuthenticatedMusicosRoute
  '/som': typeof AuthenticatedSomRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/songs/$id': typeof AuthenticatedAdminSongsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/musicos': typeof AuthenticatedMusicosRoute
  '/som': typeof AuthenticatedSomRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/songs/$id': typeof AuthenticatedAdminSongsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/musicos': typeof AuthenticatedMusicosRoute
  '/_authenticated/som': typeof AuthenticatedSomRoute
  '/api/public/time': typeof ApiPublicTimeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/songs/$id': typeof AuthenticatedAdminSongsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/musicos'
    | '/som'
    | '/api/public/time'
    | '/admin/'
    | '/admin/songs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/musicos'
    | '/som'
    | '/api/public/time'
    | '/admin'
    | '/admin/songs/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/musicos'
    | '/_authenticated/som'
    | '/api/public/time'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/songs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTimeRoute: typeof ApiPublicTimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/som': {
      id: '/_authenticated/som'
      path: '/som'
      fullPath: '/som'
      preLoaderRoute: typeof AuthenticatedSomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musicos': {
      id: '/_authenticated/musicos'
      path: '/musicos'
      fullPath: '/musicos'
      preLoaderRoute: typeof AuthenticatedMusicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/time': {
      id: '/api/public/time'
      path: '/api/public/time'
      fullPath: '/api/public/time'
      preLoaderRoute: typeof ApiPublicTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/songs/$id': {
      id: '/_authenticated/admin/songs/$id'
      path: '/admin/songs/$id'
      fullPath: '/admin/songs/$id'
      preLoaderRoute: typeof AuthenticatedAdminSongsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMusicosRoute: typeof AuthenticatedMusicosRoute
  AuthenticatedSomRoute: typeof AuthenticatedSomRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSongsIdRoute: typeof AuthenticatedAdminSongsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMusicosRoute: AuthenticatedMusicosRoute,
  AuthenticatedSomRoute: AuthenticatedSomRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSongsIdRoute: AuthenticatedAdminSongsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTimeRoute: ApiPublicTimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
